export const PROJECT_REQUEST = "PROJECT_REQUEST";
export const PROJECT_SUCCESS = "PROJECT_SUCCESS";
export const PROJECT_ERROR = "PROJECT_ERROR";


export const CLIENTS_REQUEST = "CLIENTS_REQUEST";
export const CLIENTS_SUCCESS = "CLIENTS_SUCCESS";
export const CLIENTS_ERROR = "CLIENTS_ERROR";